import 'package:dartchess/dartchess.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:centipawn/services/critical_moments/critical_moments.dart';
import 'package:centipawn/services/pgn_parser.dart';

/// End-to-end Stage C over a real game.
///
/// The engine is simulated — but every PV is generated by actually walking
/// dartchess from the position, so the lines are legal and the divergence walk,
/// the gates and the ranking all see the same shapes they would in production.
/// This is the test that catches "the pipeline runs but nothing ever survives
/// the gates", which unit tests on single plies cannot.

/// The Opera Game — one of the five seeded games, and a forced mate at the end.
const operaGame = '1. e4 e5 2. Nf3 d6 3. d4 Bg4 4. dxe5 Bxf3 5. Qxf3 dxe5 '
    '6. Bc4 Nf6 7. Qb3 Qe7 8. Nc3 c6 9. Bg5 b5 10. Nxb5 cxb5 '
    '11. Bxb5+ Nbd7 12. O-O-O Rd8 13. Rxd7 Rxd7 14. Rd1 Qe6 '
    '15. Bxd7+ Nxd7 16. Qb8+ Nxb8 17. Rd8# 1-0';

/// Plays [count] legal moves from [fen], always taking the first legal move.
/// Produces a legal continuation of realistic length without needing an engine.
List<String> _lineFrom(String fen, int count, {String? firstMove}) {
  Position pos;
  try {
    pos = Chess.fromSetup(Setup.parseFen(fen));
  } catch (_) {
    return const [];
  }
  final out = <String>[];

  if (firstMove != null) {
    final m = NormalMove.fromUci(firstMove);
    if (pos.isLegal(m)) {
      out.add(firstMove);
      pos = pos.play(m);
    }
  }

  while (out.length < count) {
    NormalMove? pick;
    for (final entry in pos.legalMoves.entries) {
      for (final to in entry.value.squares) {
        var candidate = NormalMove(from: entry.key, to: to);
        if (pos.board.roleAt(entry.key) == Role.pawn &&
            (to.rank == Rank.eighth || to.rank == Rank.first)) {
          candidate = candidate.withPromotion(Role.queen);
        }
        if (pos.isLegal(candidate)) {
          pick = candidate;
          break;
        }
      }
      if (pick != null) break;
    }
    if (pick == null) break;
    out.add(pick.uci);
    pos = pos.play(pick);
  }
  return out;
}

/// An alternative first move that is not [avoid], for the second PV.
String? _altMove(String fen, String avoid) {
  final pos = Chess.fromSetup(Setup.parseFen(fen));
  for (final entry in pos.legalMoves.entries) {
    for (final to in entry.value.squares) {
      final m = NormalMove(from: entry.key, to: to);
      if (!pos.isLegal(m)) continue;
      if (m.uci.substring(0, 4) == avoid.substring(0, 4)) continue;
      return m.uci;
    }
  }
  return null;
}

/// Attaches plausible engine output to every ply.
///
/// [mateFromPly] makes the tail of the game a forced mate, which is what the
/// seeded games actually are.
void simulateEngine(
  List<PlyData> plies, {
  int Function(int)? gapAt,
  int? mateFromPly,
}) {
  for (int i = 0; i < plies.length; i++) {
    final p = plies[i];
    final best = _lineFrom(p.fenBefore, 12, firstMove: p.movePlayedUci);
    final altFirst = _altMove(p.fenBefore, p.movePlayedUci);
    final alt = altFirst == null
        ? <String>[]
        : _lineFrom(p.fenBefore, 12, firstMove: altFirst);

    final gap = gapAt?.call(i) ?? (20 + (i * 37) % 200);
    final settle = 4 + (i * 5) % 18;

    int? mate;
    if (mateFromPly != null && i >= mateFromPly) {
      // Distance shrinks towards the end, alternating sign by side to move.
      final movesLeft = ((plies.length - i) / 2).ceil();
      mate = p.side == plies[mateFromPly].side ? movesLeft : -movesLeft;
    }

    final result = SearchResult(
      fen: p.fenBefore,
      depth: 28,
      legalMoveCount: Chess.fromSetup(Setup.parseFen(p.fenBefore))
          .legalMoves
          .values
          .fold<int>(0, (s, set) => s + set.size),
      inCheck: Chess.fromSetup(Setup.parseFen(p.fenBefore)).isCheck,
      pvs: [
        PvLine(movesUci: best, scoreCp: mate == null ? gap : 0, mateIn: mate),
        if (alt.isNotEmpty)
          PvLine(
            movesUci: alt,
            scoreCp: mate == null ? 0 : 0,
            mateIn: mate == null ? null : (mate > 0 ? mate + 2 : mate - 2),
          ),
      ],
      bestByDepth: {
        for (int d = 1; d <= 28; d++)
          d: d >= settle ? best.first : (altFirst ?? best.first),
      },
    );
    p.shallow = result;
    p.deep = result;
  }
}

void main() {
  group('a real game produces critical moments', () {
    late List<PlyData> plies;

    setUp(() {
      final tree = PgnParser.parsePgn(operaGame);
      plies = PlyBuilder.fromMainline(tree.mainline);
    });

    test('the game parses into plies for both sides', () {
      expect(plies.length, 33); // 17 white moves, 16 black
      expect(plies.first.side, Side.white);
      expect(plies.first.movePlayedSan, 'e4');
      expect(plies.last.movePlayedSan, 'Rd8#');
    });

    test('scoring yields a non-empty ranking', () {
      simulateEngine(plies);
      final report =
          const CriticalMomentScorer().score(plies, Side.white);

      expect(report.allScored, isNotEmpty,
          reason: 'every white ply was zeroed — a gate is over-firing');
      expect(report.moments, isNotEmpty);
      // Scores must actually discriminate, not all collapse to one value.
      final distinct = report.allScored.map((m) => m.rawScore).toSet();
      expect(distinct.length, greaterThan(1));
    });

    test('reports at most five moments', () {
      simulateEngine(plies);
      final report = const CriticalMomentScorer().score(plies, Side.white);
      expect(report.moments.length, lessThanOrEqualTo(5));
    });

    test('a forced mate finish does not monopolise the report', () {
      // The seeded games all end in forced mates. If the mate-run gate fails,
      // the tail of the game fills the entire top five.
      simulateEngine(plies, mateFromPly: 24);
      final report = const CriticalMomentScorer().score(plies, Side.white);

      final tailMoments =
          report.moments.where((m) => m.ply >= 24).length;
      expect(tailMoments, lessThan(report.moments.length),
          reason: 'the mating sequence crowded out the whole report');

      final mateZeroed =
          report.zeroed.where((z) => z.reason == 'forced:mate_run').toList();
      expect(mateZeroed, isNotEmpty,
          reason: 'mate-run suppression never fired on a forced mate finish');
    });

    test('gate attribution is populated for every zeroed ply', () {
      simulateEngine(plies, mateFromPly: 24);
      final report = const CriticalMomentScorer().score(plies, Side.white);
      for (final z in report.zeroed) {
        expect(z.reason, isNotEmpty);
        expect(z.movePlayedSan, isNotEmpty);
      }
    });

    test('only white plies are scored when analysing white', () {
      simulateEngine(plies);
      final report = const CriticalMomentScorer().score(plies, Side.white);
      final allPlies = {
        ...report.allScored.map((m) => m.ply),
        ...report.zeroed.map((z) => z.ply),
      };
      expect(allPlies.every((p) => p.isEven), isTrue);
    });

    test('analysing black gives a different ranking', () {
      simulateEngine(plies);
      final white = const CriticalMomentScorer().score(plies, Side.white);
      final black = const CriticalMomentScorer().score(plies, Side.black);
      expect(black.allScored.map((m) => m.ply).every((p) => p.isOdd), isTrue);
      expect(black.allScored.map((m) => m.ply).toSet(),
          isNot(equals(white.allScored.map((m) => m.ply).toSet())));
    });

    test('no clock data means no regression, but still a ranking', () {
      // The seeded games carry no [%clk] tags at all.
      simulateEngine(plies);
      final report = const CriticalMomentScorer().score(plies, Side.white);
      expect(report.regressionRan, isFalse);
      expect(report.meanResidualTopQuartile, isNull);
      expect(report.allScored, isNotEmpty);
      expect(report.moments.every((m) => m.verdict == TimeVerdict.normal),
          isTrue);
    });
  });
}
